/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs.ia;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import static com.itextpdf.text.Element.CHUNK;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.draw.VerticalPositionMark;

import java.sql.Connection;
import java.sql.*;
import javax.swing.*;
import java.sql.*;
import net.proteanit.sql.DbUtils;
import javax.swing.table.DefaultTableModel;
import java.text.*;
import java.awt.print.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.PrintGraphics.*;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;
import java.util.Date;
/**
 *
 * @author Abhinav
 */
public class Billing extends javax.swing.JFrame {
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;
    /**
     * Creates new form Billing
     */
    public Billing() {
        initComponents();
        conn = javaconnect.connecrDb();
        customerCombo();
        productcombo_fill();
       
 
 Product_id();
 //date1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        order_table = new javax.swing.JTable();
        search_tf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billing_table = new javax.swing.JTable();
        address_tf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        product_id = new javax.swing.JTextField();
        productCombo = new javax.swing.JComboBox();
        txt_amount = new javax.swing.JTextField();
        txt_gst = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        txt_quantity = new javax.swing.JTextField();
        customerID_combo = new javax.swing.JComboBox();
        amountCalc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_hsn = new javax.swing.JTextField();
        option_done = new javax.swing.JRadioButton();
        option_due = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        grandT_tf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        BillID_tf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        date_chooser = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        totalGst_tf = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        print_button = new javax.swing.JButton();
        save_details = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        order_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(order_table);

        jLabel16.setText("Order ID");

        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search)
                    .addComponent(search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        billing_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Quantity", "GST", "HSN", "Amount"
            }
        ));
        billing_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billing_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(billing_table);

        jLabel12.setText("Address");

        productCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        productCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                productComboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        productCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productComboActionPerformed(evt);
            }
        });

        txt_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_amountActionPerformed(evt);
            }
        });

        txt_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_priceActionPerformed(evt);
            }
        });

        customerID_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        customerID_combo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                customerID_comboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        customerID_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerID_comboActionPerformed(evt);
            }
        });

        amountCalc.setText("jButton6");
        amountCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountCalcActionPerformed(evt);
            }
        });

        jLabel2.setText("product Name");

        jLabel1.setText("Customer ID");

        jLabel6.setText("GST");

        jLabel5.setText("Quantity");

        jLabel11.setText("Name");

        jLabel4.setText("Price");

        jLabel3.setText("Product ID");

        jLabel7.setText("AMOUNT");

        jLabel9.setText("HSN code");

        txt_hsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hsnActionPerformed(evt);
            }
        });

        buttonGroup1.add(option_done);
        option_done.setText("DONE");
        option_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option_doneActionPerformed(evt);
            }
        });

        buttonGroup1.add(option_due);
        option_due.setText("DUE");

        jLabel8.setText("Payment Status");

        jLabel13.setText("GRAND TOTAL");

        jLabel14.setText("Bill No.");

        jLabel17.setText("Date");

        date_chooser.setDateFormatString("yyyy-MM-dd");

        jLabel15.setText("TOTAL TAX");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(option_due, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(10, 10, 10)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(option_done, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_hsn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(252, 252, 252)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalGst_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(grandT_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(product_id, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_amount, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                        .addComponent(txt_gst))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BillID_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(productCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(customerID_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(127, 127, 127)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(date_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(address_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(amountCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BillID_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(customerID_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(address_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(name_tf)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(product_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountCalc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(option_done, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(option_due)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 34, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_hsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grandT_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalGst_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        menu.setText("MENU");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        print_button.setText("PRINT");
        print_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_buttonActionPerformed(evt);
            }
        });

        save_details.setText("SAVE INVOICE");
        save_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_detailsActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 51, 0));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("BILLING");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear))
                .addGap(8, 8, 8)
                .addComponent(update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(163, 163, 163)
                .addComponent(print_button)
                .addGap(18, 18, 18)
                .addComponent(save_details)
                .addGap(157, 157, 157))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(print_button)
                            .addComponent(save_details))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add)
                            .addComponent(update)
                            .addComponent(delete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clear)
                            .addComponent(menu))
                        .addGap(44, 44, 44))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void quantity(){
    DefaultTableModel model = (DefaultTableModel) billing_table.getModel();
   int row = billing_table.getRowCount();
    for(int a =0;a<row;a++){
        String ID = (String) billing_table.getValueAt(a,0);
        try{
            String sql = " select * from stockinventory where productID ='"+ID+"'";
            pst= conn.prepareStatement(sql);
            rs= pst.executeQuery();
            try{
                String qOld = rs.getString("quantityA");
                int QOld = Integer.parseInt(qOld);
                String q1 = (String)model.getValueAt(a, 3);
                int Q1 = Integer.parseInt(q1);
                int qNew = QOld-Q1;
                String Qfinal = Integer.toString(qNew);
                try{
                    String sql1 = "update stockinventory set quantityA ='"+Qfinal+"' where productID = '"+ID+"'";
                    pst = conn.prepareStatement(sql1);
                    pst.executeUpdate();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"UPDATED");
        }
    }
}
    public void Product_id(){
        try{
           
            String sql = "select max(BillID) from BillID";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if(rs.next()){
               int old_id = rs.getInt(1);
               int new_id = old_id + 1;
               String ab = Integer.toString(new_id);
               BillID_tf.setText(ab);
          
            }
            
            
          
               rs.close();
               pst.close();
        }catch(Exception e){
        
        JOptionPane.showMessageDialog(null,e);
        }
        finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
        }
        }
    }
    private void productcombo_fill(){
    try{
    String sql = "select * from stockinventory";
    pst = conn.prepareStatement(sql);
    rs = pst.executeQuery();
    
    while(rs.next()){
        String productName = rs.getString("productname");
       productCombo.addItem(productName);
       
    }
    
   
               rs.close();
               pst.close();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
}
   private void datele(){
    java.util.Date dt = new java.util.Date();

java.text.SimpleDateFormat sdf = 
     new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

String currentTime = sdf.format(dt);
   } 
/** public void date1(){
    Calendar cal = new GregorianCalendar();
    int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
            int day = cal.get(Calendar.DAY_OF_MONTH);
            date_txt.setText(year+"/"+month+"/"+day);
} */
    
private void customerCombo(){
    try{
    String sql = "select * from customerInventory";
    pst = conn.prepareStatement(sql);
    rs = pst.executeQuery();
    
    while(rs.next()){
        String customerID = rs.getString("CustomerID");
        customerID_combo.addItem(customerID);
    }
    
    
  
               rs.close();
               pst.close();
    }catch(Exception e){
        
        JOptionPane.showMessageDialog(null,e);
            
            }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
}
public void Date(){
    Calendar cal = new GregorianCalendar();

}
/**  
private void update_table(){
        try{
            
        String sql = "select * from billing";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
          billing_table.setModel(DbUtils.resultSetToTableModel(rs));
          
        product_id.setText(null);
        txt_price.setText(null);
        txt_gst.setText(null);
        txt_hsn.setText(null);
        txt_quantity.setText(null);
        txt_amount.setText(null);
       
        
        

               rs.close();
               pst.close();
          
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
  
    }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
    }
    */
  private void TotalGST(){
    Double total = 0.0;
    String display_total = " ";
    for(int a =0;a<billing_table.getRowCount();a++){
        double grand = Double.parseDouble(billing_table.getValueAt(a,6)+"");
    total = total+grand;
    display_total = Double.toString(total);
            }
    grandT_tf.setText(display_total);
}
  
    private void txt_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_amountActionPerformed
/***/
    private void txt_hsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hsnActionPerformed

    private void productComboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_productComboPopupMenuWillBecomeInvisible
String tmp = (String)productCombo.getSelectedItem();
String sql = "select * from stockinventory where productname=?";

try{
    pst = conn.prepareStatement(sql);
    pst.setString(1, tmp);
    rs = pst.executeQuery();

if(rs.next()){
String add = rs.getString("productID");
product_id.setText(add);
String add2 = rs.getString("Price");
txt_price.setText(add2);        
String add3 = rs.getString("GST");
txt_gst.setText(add3);
String add4 = rs.getString("HSNcode");
txt_hsn.setText(add4);



               rs.close();
               pst.close();
}
}catch(Exception e){
    JOptionPane.showMessageDialog(null,e);
}finally{
            try{
                rs.close();
                pst.close();
                
                
              
            }catch(Exception e){
                
            }
        }

    }//GEN-LAST:event_productComboPopupMenuWillBecomeInvisible

    private void productComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productComboActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
menu info = new menu();
info.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

     /**   
        try{
            String sql = "Insert into billing(productID,Name,Price,Quantity,GST,Amount,HSN) values(?,?,?,?,?,?,?)";
        
pst = conn.prepareStatement(sql);

  pst.setString(1,product_id.getText());
  pst.setString(2, (String) productCombo.getSelectedItem());
            pst.setString(3,txt_price.getText());
            pst.setString(4,txt_quantity.getText());
            pst.setString(5,txt_gst.getText());
            pst.setString(6,txt_amount.getText());
            pst.setString(7,txt_hsn.getText());
            
            pst.execute();
            update_table();
            TotalGST();
            
            
         
               rs.close();
               pst.close(); 
        } catch(Exception e){
JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
        */
// TODO add your handling code here:
 if(product_id.getText().trim().isEmpty() || txt_price.getText().trim().isEmpty() || txt_quantity.getText().trim().isEmpty() || txt_gst.getText().trim().isEmpty() || txt_hsn.getText().trim().isEmpty()){
     JOptionPane.showMessageDialog(null,"Enter All fields");
 }   else{
     
     
     String productID = product_id.getText();
     Object productN = productCombo.getSelectedItem();
     String price = txt_price.getText();
     String quantity = txt_quantity.getText();
     String gst =txt_gst.getText();
     String amount = txt_amount.getText();
     String hsn = txt_hsn.getText();
     
     Object[] row = {productID,productN,price,quantity,gst,hsn,amount};
     DefaultTableModel model = (DefaultTableModel) billing_table.getModel();
     model.addRow(row);
     product_id.setText(" ");
     txt_price.setText(" ");
     txt_quantity.setText(null);
     txt_gst.setText(" ");
     txt_amount.setText(" ");
     txt_hsn.setText(" ");
     productCombo.setSelectedIndex(0);
     product_id.setText(" ");
     TotalGST();
 }
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
int msg = JOptionPane.showConfirmDialog(null,"Confirm if you want to delete","DELETE",JOptionPane.YES_NO_OPTION);    
if(msg==0){
DefaultTableModel model = (DefaultTableModel) billing_table.getModel();

try{
int delete = billing_table.getSelectedRow();
model.removeRow(delete);
product_id.getText();
        txt_price.setText(" ");
        txt_quantity.setText(null);
        txt_gst.setText(" ");
        txt_amount.setText(" ");
        txt_hsn.setText(" ");
        productCombo.setSelectedIndex(0);
        product_id.setText(null);
TotalGST();



               rs.close();
               pst.close();
}catch(Exception e){
    
    JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
}  // TODO add your handling code here:
                                           // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void billing_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billing_tableMouseClicked
DefaultTableModel model = (DefaultTableModel) billing_table.getModel();
int display = billing_table.getSelectedRow();
product_id.setText(model.getValueAt(display,0).toString());
txt_price.setText(model.getValueAt(display,2).toString());
txt_quantity.setText(model.getValueAt(display,3).toString());
txt_gst.setText(model.getValueAt(display,4).toString());
txt_hsn.setText(model.getValueAt(display,5).toString());
txt_amount.setText(model.getValueAt(display,6).toString());
        
        /**
        
         try{
    int row = billing_table.getSelectedRow();
    
String Table_click = (billing_table.getModel().getValueAt(row, 0).toString());
String sql = "select * from billing where ProductID = '"+Table_click+"' ";

pst = conn.prepareStatement(sql);
rs = pst.executeQuery();




if(rs.next()){
String add1 = rs.getString("productID");
product_id.setText(add1);
String add2 = rs.getString("Price");
txt_price.setText(add2);
String add3 = rs.getString("quantity");
txt_quantity.setText(add3);
String add4 = rs.getString("GST");
txt_gst.setText(add4);
String add5 = rs.getString("Amount");
txt_amount.setText(add5);
String add6 = rs.getString("HSN");
txt_hsn.setText(add6);

 rs.close();
                     pst.close();
                   
}
}catch(Exception e){
    JOptionPane.showMessageDialog(null,e);
    
    
} finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        } */
        
    }//GEN-LAST:event_billing_tableMouseClicked

    private void txt_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_priceActionPerformed

    private void amountCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountCalcActionPerformed

   String gst = txt_gst.getText();
   double gstInt;
   gstInt = Integer.parseInt(gst);
   
   
   String price = txt_price.getText();
   int priceInt;
   priceInt = Integer.parseInt(price);
   
   
   String quantity = txt_quantity.getText();
   int quantityInt;
   quantityInt = Integer.parseInt(quantity);

double amount;
amount = (priceInt*quantityInt);

double gstPrice;
gstPrice = (amount + ((gstInt/100)*amount));

String Amount_Int = Double.toString(gstPrice);
txt_amount.setText(Amount_Int);

        //TODO add your handling code here:
    }//GEN-LAST:event_amountCalcActionPerformed

    private void option_doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option_doneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option_doneActionPerformed

    private void print_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_buttonActionPerformed
try{
    Document print = new Document();
    PdfWriter.getInstance(print,new FileOutputStream("invoice.pdf"));
    print.open();
    Date date = date_chooser.getDate();
    String str = DateFormat.getDateInstance().format(date);
    
    Image image = Image.getInstance("apple.png");
    image.setAlignment(image.ALIGN_CENTER);
    print.add((Element) image);
    
            Paragraph p = new Paragraph();
            p.add("INDUSTRIAL MARKETING");
            p.setAlignment(Paragraph.ALIGN_CENTER);
            
            Paragraph d = new Paragraph();
            d.add("_________________________________________");
            d.setAlignment(Paragraph.ALIGN_CENTER);
            
            Paragraph e = new Paragraph();
            e.add("Block No 8, Flat No 43, LF Type, Road No 10, Rajendranagar, Patna - 800016, Opposite Gulzar Mansion ");
            e.setAlignment(Paragraph.ALIGN_CENTER);
            
            Paragraph g = new Paragraph();
            g.add("Payment Done : ");
            
            Chunk set = new Chunk(new VerticalPositionMark());
            Paragraph name = new Paragraph("Customer Name: "+ name_tf.getText());
           
            name.add(new Chunk(set));
            name.add("INVOICE ID : " + BillID_tf.getText());
            
            
            Chunk set1 = new Chunk(new VerticalPositionMark());
            Paragraph address = new Paragraph("Customer Address : " + address_tf.getText());
            address.add(new Chunk(set1));
            address.add("Date : " + str);
           
            
            Paragraph blank = new Paragraph();
            blank.add(" ");
            
            Paragraph info = new Paragraph();
            info.add(new Chunk("\n OUR SBI ACC. NO.:- 31887786832 "));
            info.add(new Chunk("\n RAJENDRA NAGAR, PATNA "));
            info.add(new Chunk("\n VENDOR CODE: DOLA 4052434 "));
            info.add(new Chunk("\n GST NO: 10ADJPK6897M1ZZ "));
            
            Paragraph sign = new Paragraph();
            sign.add("BRANCH MANAGER'S SIGNATURE AND STAMP : ");
            sign.setAlignment(Paragraph.ALIGN_RIGHT);
            
            
            
            print.add(p);
            print.add(d);
            print.add(e);
            print.add(blank);
            print.add(name); print.add(address);
            print.add(Chunk.NEWLINE);
           
            int a  = billing_table.getColumnCount();
            PdfPTable table = new PdfPTable(a);
            for(int i=0; i<a;i++){
                table.addCell(billing_table.getColumnName(i));
            }
            for(int row = 0; row<billing_table.getRowCount(); row++){
                for(int col = 0; col<a; col++){
                    table.addCell(billing_table.getModel().getValueAt(row,col).toString());
                }
            }
            
    print.add(table);
    print.add(blank);
    print.add(info);
    print.add(blank);
    print.add(blank);
    print.add(sign);
    JOptionPane.showMessageDialog(null,"SAVED");
    print.close();
} catch(Exception e){
    JOptionPane.showMessageDialog(null,e);
}      
    /**    
        MessageFormat header = new MessageFormat("BILL INVOICE");
        MessageFormat footer = new MessageFormat("page{0,number,integer}");
        try{
            billing_table.print( JTable.PrintMode.NORMAL,header , footer);

        } catch(java.awt.print.PrinterException e){
       System.err.format("Cannot Print ", e.getMessage());
        } */
    }//GEN-LAST:event_print_buttonActionPerformed

    private void save_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_detailsActionPerformed

        
        boolean DoneSelected = option_done.isSelected();
boolean DueSelected = option_due.isSelected();
        if(DoneSelected){
             try{
                Calendar calendar = Calendar.getInstance();
      java.sql.Date startDate = new java.sql.Date(calendar.getTime().getTime());
 
           
            String sql = "Insert into PaymentDone(BillID,CustomerName,CustomerID,Amount,Date) values(?,?,?,?,?)";
        
pst = conn.prepareStatement(sql);
//pst.setString(1,OrderID_tf.getText());
pst.setString(1,BillID_tf.getText());
pst.setString(2,name_tf.getText());
String value = customerID_combo.getSelectedItem().toString();
pst.setString(3,value);
pst.setString(4,grandT_tf.getText());
pst.setString(5, ((JTextField)date_chooser.getDateEditor().getUiComponent()).getText());
//pst.setString(6,totalGst_tf.getText());
//pst.setDate(5,startDate);

            pst.execute();
            quantity();
            Product_id();
            
            JOptionPane.showMessageDialog(null, "SAVED to PAYMENT DONE");
            
            
          
               rs.close();
               pst.close();
        } catch(Exception e){
JOptionPane.showMessageDialog(null,e);
        
        } 
        } else if(DueSelected){
           try{
            String sql = "Insert into PaymentDue(BillID,CustomerName,CustomerID,Amount,Date) values(?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
// pst.setString(1,OrderID_tf.getText());
pst.setString(1,BillID_tf.getText());
pst.setString(2,name_tf.getText());
String value = customerID_combo.getSelectedItem().toString();
pst.setString(3,value);
pst.setString(4,grandT_tf.getText());
pst.setString(5, ((JTextField)date_chooser.getDateEditor().getUiComponent()).getText());
//pst.setString(6,totalGst_tf.getText());
//pst.setString(7,Date_tf.getText());

            pst.execute();
              quantity();
             JOptionPane.showMessageDialog(null, "SAVED to PAYMENT DUE");
             
             
          
              
        } catch(Exception e){
JOptionPane.showMessageDialog(null,e);
        
        }   
            
        
       }
       try{
        String sql =  "Insert into BillID(BillID) values(?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1,BillID_tf.getText());
            pst.execute();
            Product_id();
            
       } catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
       
            // TODO add your handling code here:
    }//GEN-LAST:event_save_detailsActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void customerID_comboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_customerID_comboPopupMenuWillBecomeInvisible
String tmp = (String)customerID_combo.getSelectedItem();
String sql = "select * from customerInventory where CustomerID=?";

try{
    pst = conn.prepareStatement(sql);
    pst.setString(1, tmp);
    rs = pst.executeQuery();

if(rs.next()){
String add = rs.getString("Name");
name_tf.setText(add);
String add2 = rs.getString("Address");
address_tf.setText(add2);        
//String add3 = rs.getString("Contact");
//txt_gst.setText(add3);




               rs.close();
               pst.close();
}
}catch(Exception e){
    JOptionPane.showMessageDialog(null,e);
}finally{
            try{
                rs.close();
                pst.close();
                
                
              
            }catch(Exception e){
                
            }
        }

            // TODO add your handling code here:
    }//GEN-LAST:event_customerID_comboPopupMenuWillBecomeInvisible

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
 try{
        String sql = "select * from orderlist where orderID =?";
        
        pst = conn.prepareStatement(sql);
        pst.setString(1,search_tf.getText());
        
        rs = pst.executeQuery();
        
       
   /** if(rs.next()==false){
        JOptionPane.showMessageDialog(null, "no results");
    } else{ */
             order_table.setModel(DbUtils.resultSetToTableModel(rs));
      
            } catch(Exception e){
JOptionPane.showMessageDialog(null, e);
        
                }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }// TODO add your handling code here:
                                                 // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void customerID_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerID_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerID_comboActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
product_id.setText(null);
txt_price.setText(null);
txt_quantity.setText(null);
txt_gst.setText(null);
txt_amount.setText(null);
txt_hsn.setText(null);
productCombo.setSelectedIndex(0);
customerID_combo.setSelectedIndex(0);
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BillID_tf;
    private javax.swing.JButton add;
    private javax.swing.JTextField address_tf;
    private javax.swing.JButton amountCalc;
    private javax.swing.JTable billing_table;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox customerID_combo;
    private com.toedter.calendar.JDateChooser date_chooser;
    private javax.swing.JButton delete;
    private javax.swing.JTextField grandT_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton menu;
    private javax.swing.JTextField name_tf;
    private javax.swing.JRadioButton option_done;
    private javax.swing.JRadioButton option_due;
    private javax.swing.JTable order_table;
    private javax.swing.JButton print_button;
    private javax.swing.JComboBox productCombo;
    private javax.swing.JTextField product_id;
    private javax.swing.JButton save_details;
    private javax.swing.JButton search;
    private javax.swing.JTextField search_tf;
    private javax.swing.JTextField totalGst_tf;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_gst;
    private javax.swing.JTextField txt_hsn;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
