/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs.ia;
import java.sql.*;
import javax.swing.*;
import java.sql.*;
import net.proteanit.sql.DbUtils;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Abhinav
 */
public class inventory extends javax.swing.JFrame {
Connection conn = null;
ResultSet rs = null;
        PreparedStatement pst = null;
    /**
     * Creates new form inventory
     */
    public inventory() {
        initComponents();
       update_table();
       Product_id();
    }
    
    public void Product_id(){
        try{
         String url = "jdbc:sqlite:C:\\Users\\Abhinav\\Desktop\\apple.db";
         conn= DriverManager.getConnection(url);
            String sql = "select max(productID) from stockinventory";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if(rs.next()){
               int old_id = rs.getInt(1);
               int new_id = old_id + 1;
               String ab = Integer.toString(new_id);
               productID_tf.setText(ab);
              
               rs.close();
               pst.close();
            }
        }catch(Exception e){
        
        JOptionPane.showMessageDialog(null,e);
        
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }
    private void reorder(){
       String ord = (String)order.getSelectedItem(); 
       int ord1 = Integer.parseInt(ord);
       try{
           String sql= "select productname,productID,quantityA,Price,GST,HSNcode from stockinventory where quantityA<=' "+ord1+"'";
           pst = conn.prepareStatement(sql);
           rs=pst.executeQuery();
           reorder.setModel(DbUtils.resultSetToTableModel(rs));
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
    }
    private void update_table(){
        try{
           String url = "jdbc:sqlite:C:\\Users\\Abhinav\\Desktop\\apple.db";
         conn= DriverManager.getConnection(url);
        String sql = "select * from stockinventory";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
          Table_inventory.setModel(DbUtils.resultSetToTableModel(rs));
          
           productN_tf.setText(null);
        quantityAv_tf.setText(null);
        quantityA_tf.setText(null);
        price_tf.setText(null);
        gst_tf.setText(null);
        hsn_tf.setText(null);
        
       
         
             
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
  
    }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        productN_tf = new javax.swing.JTextField();
        productID_tf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        quantityAv_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        quantityA_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        price_tf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gst_tf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        hsn_tf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_inventory = new javax.swing.JTable();
        search_tf = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        searchName = new javax.swing.JButton();
        searchID = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        reorder = new javax.swing.JTable();
        order = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel3.setText("Product name");

        jLabel2.setText("Product ID");

        productID_tf.setEditable(false);

        jLabel4.setText("Quantity available");

        jLabel5.setText("Quantity added");

        jLabel6.setText("Cost Price");

        jLabel7.setText("GST(%)");

        jLabel8.setText("HSN code");

        Table_inventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_inventoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_inventory);

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        menu.setText("MENU");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        searchName.setText("SEARCH BY NAME");
        searchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameActionPerformed(evt);
            }
        });

        searchID.setText("SEARCH BY ID");
        searchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIDActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STOCK INVENTORY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        reorder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(reorder);

        order.setEditable(true);
        order.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "25", "50", "75", "100", "200" }));
        order.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                orderPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel9.setText("Reorder list");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(order, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clear, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(update)))
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(searchID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(searchName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(quantityAv_tf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(quantityA_tf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(price_tf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(gst_tf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hsn_tf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(productN_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(productID_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(productID_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(productN_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(quantityAv_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(quantityA_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(price_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(gst_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(hsn_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(delete)
                    .addComponent(update)
                    .addComponent(searchName)
                    .addComponent(search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clear)
                            .addComponent(menu)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(searchID)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(order, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
  
        try{
                     Class.forName("org.sqlite.JDBC");

            String sql = "Insert into stockinventory (productname,productID,quantityA,Price,GST,HSNcode) values (?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1,productN_tf.getText());
            pst.setString(2,productID_tf.getText());
            pst.setString(3,quantityAv_tf.getText());
            pst.setString(4,price_tf.getText());
            pst.setString(5,gst_tf.getText());
            pst.setString(6,hsn_tf.getText());
            
            pst.execute();
           
            JOptionPane.showMessageDialog(null,"saved");
            
            
               
               pst.close();
        }catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
        
        } finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }     
            
        
        update_table();
       Product_id();
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
int msg = JOptionPane.showConfirmDialog(null,"Confirm if you want to delete","DELETE",JOptionPane.YES_NO_OPTION );
if(msg==0){
        String sql = "delete from stockinventory where productID =?";
        try{
            
           
   pst = conn.prepareStatement(sql);
   pst.setString(1,productID_tf.getText());
   pst.execute();
   
   JOptionPane.showMessageDialog(null,"deleted");
   update_table();
   
   
     
               rs.close();
               pst.close();
        }
   
   catch(Exception e){
   JOptionPane.showMessageDialog(null,e);
   }finally{
                   try{
                       rs.close();
                       pst.close();
                   }catch(Exception e){
                       JOptionPane.showMessageDialog(null,e);
                   }
               }
}
   // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void Table_inventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_inventoryMouseClicked

    
         try{
    int row = Table_inventory.getSelectedRow();
    
String Table_click = (Table_inventory.getModel().getValueAt(row, 1).toString());
String sql = "select * from stockinventory where productID = '"+Table_click+" ' ";

pst = conn.prepareStatement(sql);
rs = pst.executeQuery();




if(rs.next()){
String add1 = rs.getString("productname");
productN_tf.setText(add1);
String add2 = rs.getString("productID");
productID_tf.setText(add2);
String add3 = rs.getString("quantityA");
quantityAv_tf.setText(add3);
String add4 = rs.getString("Price");
price_tf.setText(add4);
String add5 = rs.getString("GST");
gst_tf.setText(add5);
String add6 = rs.getString("HSNcode");
hsn_tf.setText(add6);

}
}catch(Exception e){
    JOptionPane.showMessageDialog(null,e);
    
    
}
finally{
                   try{
                       rs.close();
                       pst.close();
                   }catch(Exception e){
                       JOptionPane.showMessageDialog(null,e);
                   }
               }
// TODO add your handling code here:
    }//GEN-LAST:event_Table_inventoryMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        try{
            String val1 = productN_tf.getText();
            String val2 = productID_tf.getText();
            String val3 = quantityAv_tf.getText();
            String val4 = quantityA_tf.getText();
            String val5 = price_tf.getText();
            String val6 = gst_tf.getText();
            String val7 = hsn_tf.getText();
            
            int qAv = Integer.parseInt(val3);
            int qAd = Integer.parseInt(val4);
            int qFIN= (qAv+qAd);
            String qfinal = Integer.toString(qFIN);
           
            
            
            
            
             String sql = "update stockinventory set productName = '"+val1+"' ,productID ='"+val2+"' ,quantityA ='"+qfinal+"' ,Price = '"+val5+"',GST = '"+val6+"' ,HSNcode = '"+val7+"'where productID='"+val2+"'";
   pst = conn.prepareStatement(sql);
      // pst.setString(1, productID_tf.getText());
   pst.execute();
   JOptionPane.showMessageDialog(null,"updated");
   update_table();
   Product_id();
   
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
 productN_tf.setText(null);
 productID_tf.setText(null);
        quantityAv_tf.setText(null);
        quantityA_tf.setText(null);
        price_tf.setText(null);
        gst_tf.setText(null);
        hsn_tf.setText(null);
        search_tf.setText(null);
              
        Product_id();
        update_table();
                  // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
menu info = new menu();
info.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void searchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameActionPerformed
  
        try{
        String sql = "select * from stockinventory where productname =?";
        
        pst = conn.prepareStatement(sql);
        pst.setString(1,search_tf.getText());
        
        rs = pst.executeQuery();
        
       
   /** if(rs.next()==false){
        JOptionPane.showMessageDialog(null, "no results");
    } else{ */
        if(rs.next()){
            String add1 = rs.getString("productname");
            productN_tf.setText(add1);
            String add2 = rs.getString("productID");
            productID_tf.setText(add2);
            String add3 = rs.getString("quantityA");
            quantityAv_tf.setText(add3);
            String add4= rs.getString("Price");
            price_tf.setText(add4);
            String add5 = rs.getString("GST");
            gst_tf.setText(add5);
            String add6 = rs.getString("HSNcode");
            hsn_tf.setText(add6);
            
            
             
        }          
           
            } catch(Exception e){
JOptionPane.showMessageDialog(null, e);
        
                }finally{
                   try{
                       rs.close();
                       pst.close();
                   }catch(Exception e){
                       JOptionPane.showMessageDialog(null,e);
                   }
               }
    }//GEN-LAST:event_searchNameActionPerformed

    private void searchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIDActionPerformed
 
        try{
        
            String sql = "select * from stockinventory where productID =? ";
           pst = conn.prepareStatement(sql);
           pst.setString(1, search_tf.getText());
           
           rs = pst.executeQuery();
          /**if(rs.next()==false){
    JOptionPane.showMessageDialog(null,"no such field found");}
    else{**/ 
           if(rs.next()){
               String add1 = rs.getString("productname");
               productN_tf.setText(add1);
                 String add2 = rs.getString("productID");
               productID_tf.setText(add2);
                 String add3 = rs.getString("quantityA");
               quantityAv_tf.setText(add3);
                 String add4 = rs.getString("Price");
               price_tf.setText(add4);
                 String add5 = rs.getString("GST");
               gst_tf.setText(add5);
                 String add6 = rs.getString("HSNcode");
               hsn_tf.setText(add6);
               
            
               rs.close();
               pst.close();
           }
                 
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchIDActionPerformed

    private void orderPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_orderPopupMenuWillBecomeInvisible
reorder();        // TODO add your handling code here:
    }//GEN-LAST:event_orderPopupMenuWillBecomeInvisible
    
    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_inventory;
    private javax.swing.JButton add;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JTextField gst_tf;
    private javax.swing.JTextField hsn_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton menu;
    private javax.swing.JComboBox order;
    private javax.swing.JTextField price_tf;
    private javax.swing.JTextField productID_tf;
    private javax.swing.JTextField productN_tf;
    private javax.swing.JTextField quantityA_tf;
    private javax.swing.JTextField quantityAv_tf;
    private javax.swing.JTable reorder;
    private javax.swing.JButton searchID;
    private javax.swing.JButton searchName;
    private javax.swing.JTextField search_tf;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
